import type { Queryable } from "../db";

export interface StockCountRow {
  id: string;
  location_id: number;
  product_id: number;
  /** The balance the system believed at the moment of counting. */
  theoretical_quantity: number;
  counted_quantity: number;
  /** Generated by the database as `counted − theoretical`; never written by hand. */
  difference: number;
  /** `null` when the count matched and no correction was needed. */
  movement_id: string | null;
  note: string | null;
  created_by: number;
  created_at: string;
}

export interface CreateStockCountInput {
  productId: number;
  theoreticalQuantity: number;
  countedQuantity: number;
  note: string | null;
  createdBy: number;
}

/**
 * STK-07: records the count itself. The `CORRECTION` it may produce is
 * written separately and linked back with `attachMovementToStockCount` —
 * the movement carries a reference to this row, and this row a reference to
 * the movement, so the pair can be read from either side.
 */
export async function createStockCount(
  db: Queryable,
  locationId: number,
  input: CreateStockCountInput,
): Promise<StockCountRow> {
  const {
    rows: [row],
  } = await db.query<StockCountRow>(
    `INSERT INTO stock_counts
       (location_id, product_id, theoretical_quantity, counted_quantity, note, created_by)
     VALUES ($1, $2, $3, $4, $5, $6)
     RETURNING *`,
    [
      locationId,
      input.productId,
      input.theoreticalQuantity,
      input.countedQuantity,
      input.note,
      input.createdBy,
    ],
  );
  return row;
}

/**
 * `movementId` is typed loosely on purpose: `stock_movements.id` is a
 * `BIGINT`, which pg hands back as a string, while `StockMovementRow`
 * declares it a `number`. The declaration is the inaccurate one — narrowing
 * here would mean asserting a lie rather than accepting the value the
 * database actually returns.
 */
export async function attachMovementToStockCount(
  db: Queryable,
  locationId: number,
  countId: string,
  movementId: string | number,
): Promise<StockCountRow> {
  const {
    rows: [row],
  } = await db.query<StockCountRow>(
    "UPDATE stock_counts SET movement_id = $3 WHERE id = $1 AND location_id = $2 RETURNING *",
    [countId, locationId, movementId],
  );
  return row;
}

export interface StockCountHistoryRow extends StockCountRow {
  counted_by_name: string | null;
}

/**
 * The five figures STK-07 requires be consultable — stock avant, compté,
 * différence, auteur, date — for one product, most recent first.
 */
export async function listStockCounts(
  db: Queryable,
  locationId: number,
  productId: number,
  limit = 20,
): Promise<StockCountHistoryRow[]> {
  const { rows } = await db.query<StockCountHistoryRow>(
    `SELECT c.*, u.name AS counted_by_name
     FROM stock_counts c
     LEFT JOIN users u ON u.id = c.created_by
     WHERE c.location_id = $1 AND c.product_id = $2
     ORDER BY c.created_at DESC, c.id DESC
     LIMIT $3`,
    [locationId, productId, limit],
  );
  return rows;
}
